### ISSUE TITLE
Improve build toolchain

### ISSUE THREAD

**Issue by jsilvestre** [jsilvestre/tasky#27]
I think the current way to build / dev the app can be drastically improved. Brunch is very nice and all, but I think we should replace it from something like npm+browserify.

**Comment by frankrousseau** [comment]
Some remarks:

* Including build result in the versioned repository doesn't make sense for most of web app deployments. But we don't do tradionial SaaS softwares. In our case, running a builds on every machine that runs cozy is a bad practice too. 
* The real question is: should we use git as a package manager ?
* Someone who performed a build, performed an action that makes sense for us. It's good to see this person appearing in the commit log.
* About the credit part, a build often comes from someone who at least tested the code, who contributed to it in a more significant way than just running a build command.
* I think @substack is right. Use programming tools instead of simple script tools to perform build commands is overkill. 
* Bash does the job well and a lot of people understand it. So the combo npm + bash looks good to solve our problem. 
* I prefer it over task runners.
* Brunch fits well with our needs. Despite the fact, it doesn't fit with the two previous points, we shoulnd't throw it too easily.

**Comment by jsilvestre** [comment]
So it works well, but it's still slower than Brunch. I'm really looking forward Brunch 1.8, that will bring browserify support, because I can't code without browserify anymore. I'm closing!
